# Generated by Django 4.2.7 on 2023-11-28 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_userprofile_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
