# Generated by Django 4.2.7 on 2023-11-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_remove_userprofile_email_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='images/default_pic.jpg', null=True, upload_to='images/'),
        ),
    ]
